### ISSUE TITLE
AirModel 能否支持类型嵌套呢？

### ISSUE THREAD

**Issue by xpsuper** [HammCn/AirPower#2]
AirModel 非常好用，但没有支持类型嵌套有点可惜，比如：

```
class Info extends AirModel {
      id!: number
      @Type(String)
      phone!: string
}

class User extends AirModel {
     name!: string
     info: Info
     infoList: []Info
}
```

这种就不支持了，可惜

**Comment by HammCn** [comment]
你好，感谢支持。

嵌套也是支持的哈，在被嵌套的属性上标记@Type 装饰器，传入嵌套类的类名即可。

再次感谢关注

**Comment by xpsuper** [comment]
不好意思，没有仔细看，的确支持类型嵌套，这个库非常好用，👍

**Comment by HammCn** [comment]
这个库提供的是一个工具包，如果你计划一个全新的后台管理类的前端脚手架的话，也欢迎关注我们另外的两个项目：

- 前端： https://github.com/HammCn/AirPower4T
- 后端： https://github.com/HammCn/AirPower4J
